### ISSUE TITLE
Option to make new tool types (hoe)

### ISSUE THREAD

**Issue by Lordician** [tyra314/ToolProgression#10]
Hey there, i have been tweaking some things and how odd it may sound, i am trying to make some crops only able to be broken/harvested with hoes of a certain tier.
Adding the harvest level and tool type requirement worked for the crop blocks (they also showed up in the blocks config file) and i cannot break crops without a hoe with the right tier.
However, it does not seem to detect the hoes' harvest level i gave them, nor the tool type.
Then again, i manually added the hoes to the tool overwrite config file due to them not showing in the tool config file...

Can you add this or fix this if it is a bug?
It would be great, i tried this mod after the other similar mod: Harvest Tweaks and so far i came closer to doing what i want then with the other mod.

I even tried this without all my other mods, just the barebones, this & HWYLA (Waila fork).
Here are the config files i used:
[tool_progression.zip](https://github.com/tyra314/ToolProgression/files/1435796/tool_progression.zip)
And these are the logs from when i tried it.
[2017-11-01-3.log.gz](https://github.com/tyra314/ToolProgression/files/1435800/2017-11-01-3.log.gz)
Seems like the hoes do not even get looked at.
If you want one of the log files or config files seperatly, do say, not everybody trusts zip files uploaded on github which is fair enough.

Minecraft version: 1.12.2
Forge version: 14.23.0.2512
Mod version: 1.12-1.2.11

**Comment by tyra314** [comment]
Should be fixed in the [new version 1.3.0](https://minecraft.curseforge.com/projects/tool-progression/files/2496543)
