### ISSUE TITLE
Can't change Tinker's tools to new harvest levels

### ISSUE THREAD

**Issue by royalcw** [tyra314/ToolProgression#11]
I have been playing with this mod for about 3 hours now trying to figure this issue out.  I can change all the world ores to any harvest value I want.  I'm actually using 0-8 for the different mining level names file.  The one I'm working on at the moment..and once I figure it out then I'll move onto the other materials, is Copper.  I want copper to be my tier 2 material that can mine tier 3:iron.  
Under materials.cfg I have:
    # copper [default: 1]
    S:copper=3
Under blocks.cfg I have:
    # densemetals:dense_iron_ore:0 [default: pickaxe=2]
    S:"densemetals:dense_iron_ore:0"=pickaxe=3
    # minecraft:iron_ore:0 [default: pickaxe=1]
    S:"minecraft:iron_ore:0"=pickaxe=3
I'm using a copper pickaxe.  I make a brand new pickaxe everytime I restart to test it since you posted that known nbt bug about already existing tinker tools not updating with edits.  The Tinker Pickaxe always says under the nbt code "HarvestLevel:1" no mater what changes I make to copper in any of the config files.  The Tinker book also does not update to show any new harvest levels for any of the materials when I make edits to the materials.cfg file.  The Tinker book will show the new names for 0-4 of the vanilla harvest types.

I restart the game every time I change the configs and make a new Copper pickaxe each time the picks are always Harvest Level 1.  The iron blocks show a harvest level of 3 with no issues.

Minecraft Version: 1.12.2
Forge Version: 14.23.0.2522
Tool Progression:  1.3.1
No other harvest tweak type mods installed

**Comment by tyra314** [comment]
Have you made these changes in the corresponding overwrite config files? (for instance tool_progression/materials_overwrites.cfg)

**Comment by royalcw** [comment]
I made them to the materials.cfg and blocks.cfg first.  I also tried adding the lines to the overwrite file.  Then I removed the mod and deleted the config folder followed by re-download of the mod.  If they are in the overwrite file...should they be removed from the non-overwrite file?

**Comment by royalcw** [comment]
Alright, I figured it out.  I have to remove the lines from the normal file and only have the lines in the overwrite file.  I assumed the overwrite file would be the dominant file...or that changing the normal file would have set it to what I wanted.  I now see that you have to move the lines to the overwrite then delete from the normal file.  The change takes effect on restart.  Sorry to have bothered you.  I do want to say thank you for the response and that this mod is the most robust harvest editor for 1.12.2.

**Comment by tyra314** [comment]
Actually, you shouldn't have to remove the lines from the "original" file. In fact, the files `blocks.cfg`, `tools.cfg` and `materials.cfg` will be regenerated on every startup with all settings like before the overwrites are applied. The idea is that the user can simply copy from those files to the overwrite files and make their changes in the overwrite config files. Maybe I should move these files into a `generated` subfolder or something. 🤔 

> Sorry to have bothered you. I do want to say thank you for the response and that this mod is the most robust harvest editor for 1.12.2.

You're welcome.

**Comment by tyra314** [comment]
I added yet another disclaimer [here](https://github.com/tyra314/ToolProgression/wiki/Configuration-files).
But I won't move the config files for a) backward compatibility and b) I don't like the folder idea anymore. It ain't that many files anyway.
