### ISSUE TITLE
Can't make blocks minable by hand

### ISSUE THREAD

**Issue by knoxhack** [tyra314/ToolProgression#12]
Mod Version:
toolprogression-1.12.2-1.3.1
Forge:
forge-1.12.2-14.23.0.2550-universal

here is my config: 
https://gist.github.com/knoxhack/dab224c94abb6a235c0e0a7ae2022f01

**Comment by knoxhack** [comment]
Am I doing anything wrong?

**Comment by tyra314** [comment]
Not really. This is an issue, I'm aware of. I've actually fixed it in a recent commit, but I haven't made a public release yet, because I want to improve the documentation before the next release. 

If you can't wait, build current master branch on your own.

**Comment by knoxhack** [comment]
Awesome thanks for the info.

**Comment by tyra314** [comment]
Fixed in [1.4.0](https://minecraft.curseforge.com/projects/tool-progression/files/2503097).
See [the wiki](https://github.com/tyra314/ToolProgression/wiki/Block-overwrite) for details on how to configure it.
