### ISSUE TITLE
Configuration lost during upgrade

### ISSUE THREAD

**Issue by tyra314** [tyra314/ToolProgression#16]
See https://minecraft.curseforge.com/projects/tool-progression?comment=9

**Comment by Sixdd6** [comment]
Yeah the mod worked just fine before but I also updated forge on that update so that could have been what broke it, I'll do more testing.

**Comment by tyra314** [comment]
So, are the config files populated? Got they replaced? Are we talking about block, material or tool overwrites?

**Comment by Sixdd6** [comment]
Sorry, running on very little sleep. The only thing not working as intended is tool overwrites. I have Thermal Foundation steel pickaxe set to a mining level of 6 and it shows up in JEI and in inventory as level 2. I also have other tools showing incorrect mining levels as well. Block overwrites are working. Material overwrites are setup to match the tool overwrites. I made a repo [here](https://github.com/Sixdd6/reimagined-octo-meme) to show what I have right now.

**Comment by tyra314** [comment]
From a quick look, this is definitely wrong: https://github.com/Sixdd6/reimagined-octo-meme/blob/master/tool_progression/tool_overwrites.cfg#L15

The other entries look fine. I try loading Thermal Foundation in my dev env.

**Comment by Sixdd6** [comment]
I'll fix that and try again

**Comment by Sixdd6** [comment]
I changed it but the thermal foundation tools are still showing wrong mining levels as well as the redstone arsenal Fluxed Pickaxe.

**Comment by tyra314** [comment]
Yeah... I found the issue. Could never have worked for Thermal Foundation tools. It has it's one little harvest level implementation... REEEEEE

https://github.com/CoFH/CoFHCore/blob/d4a79b078d257e88414f5eed598d57490ec8e97f/src/main/java/cofh/core/item/tool/ItemToolCore.java#L44

**Comment by Sixdd6** [comment]
But doesn't this [here](https://github.com/CoFH/CoFHCore/blob/d4a79b078d257e88414f5eed598d57490ec8e97f/src/main/java/cofh/core/item/tool/ItemToolCore.java#L41) mean that the tools get their mining level from the material rather than being set directly?

**Comment by tyra314** [comment]
Yes, but this still doesn't work.

**Comment by tyra314** [comment]
Digging deeper, those Items are initialized with the Material in the TF preInit event. Material overwrites are applied in TPr postInit event, no way I could catch that. Working on a compatibility module for setting harvest levels on CoFhCore tools at least.

**Comment by Sixdd6** [comment]
ok thank you :D

**Comment by tyra314** [comment]
Should be fixed in the upcoming release [v1.4.5](https://minecraft.curseforge.com/projects/tool-progression/files/2507481)
