### ISSUE TITLE
Add TOP support

### ISSUE THREAD

**Issue by tyra314** [tyra314/ToolProgression#18]
I really should add support for TheOneProbe. FeelsBadMan

**Comment by Fireztonez** [comment]
Any information when the support for The One Probe will be done?

Your mod is awesome, works perfectly and is easy to configure!! For make your mod perfect, is miss only the support of The One Probe!! For now I have to remove The One probe and use WAILA in the modpack when I'm developing, but in the end I would like to use TOP.

**Comment by tyra314** [comment]
Well, ... apparently, a recent version of TOP works out of the box now. 🤷‍♀️ 

It wasn't me, was it?
