### ISSUE TITLE
Add ore:dict selectors

### ISSUE THREAD

**Issue by tyra314** [tyra314/ToolProgression#21]
Block- and tool overwrites should be possible to be done with oredict selectors.
For instance, `ore:oreCopper=pickaxe=3` should change all copper ores to require diamond tools. Should have the lowest precedence compared with the other selectors.

**Comment by Fireztonez** [comment]
Any news about the OreDict support for ToolProgression?? I think adding the oredict support will be really usefull When you whant to change mining level and you have a mod Like Chisel in the pack...

With oredict I can by example change all the obsidian blocks in only 1 line, but without, I have about 30 lines to made...

Fireztonez

**Comment by tyra314** [comment]
Fixed in upcoming version [v1.6.1](https://minecraft.curseforge.com/projects/tool-progression/files/2637188)

**Comment by Fireztonez** [comment]
Nice, thank's!
