### ISSUE TITLE
Snow misbehaving

### ISSUE THREAD

**Issue by Efimero** [tyra314/ToolProgression#25]
Installing Tool Progression causes snow to be unbreakable by hand.
Setting snow (layers and blocks) to =?shovel=0@0.1 causes snow to be breakable by hand, but always drop snowballs.

Snow is supposed to drop snowballs only when harvested with a shovel.
How would one acheive this while using this mod?

**Comment by tyra314** [comment]
Right now, I'm not able to look into what exactly happens with snow, but based on my understanding, this is not possible right now. I guess, what happens in vanilla is that snow is not harvestable by hand, but has such a low hardness, that it can be broken instantly anyways. However, ToolProgression enforces that you can't break blocks, which aren't harvestable.

If I'd have to suggest a setting, I'd probably go with something along what you posted. 
I'll look into it, but this may require a bit of rewriting.

**Comment by tyra314** [comment]
With the upcoming version [1.5.1](https://minecraft.curseforge.com/projects/tool-progression/files/2567741) you will be able to define a [new overwrite](https://github.com/tyra314/ToolProgression/wiki/Block-overwrite#destroyability) or use a global option.
