### ISSUE TITLE
Unable to change certain ores

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#26]
Hey!

I'm not sure this is actually a Tool Progression issue, but I thought I'd let you know regardless.
Ores from Netherending Ores and NuclearCraft cannot have their harvest level altered by Tool Progression. I've opened issues on their respective issue trackers, and it looks like they're not at fault. 

Additionally, I have previously been able to alter the harvest level of NuclearCraft ores, but lost the ability to do so 1-2 months ago.

Minecraft 1.12.2
Forge 1.12.2-14.23.2.2624
toolprogression-1.12.2-1.4.7

**Comment by tyra314** [comment]
Both mods override the method `public int getHarvestLevel(IBlockState state)` of their Blocks without also overriding the corresponding `setHarvestLevel` appropriately. This is on their end, though I might be convinced to hack something together if enough people need it.

**Comment by NillerMedDild** [comment]
I was convinced I had replied, sorry about that.

Thanks to your tip, both mods are working to fix it, thank you.
