### ISSUE TITLE
Dupe Fix Config

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#28]
Hey!

The magic anti-dupe config fixes all Tool Progression related dupes that I've found so far, but it also removes the ability to shear Mystical Tall Flowers from Botania, they simply don't drop. Would it be possible to make a fix for the flowers, or would I have to turn off the dupe config?

**Comment by tyra314** [comment]
This dupe "fix" is actually the worst hack I've ever done, so I'm actually surprised that it fixes the dupes and only causes one issue LUL

Right now I'm not in the mood for doing any dev works, but I'd suggest trying to give the flowers a shear toolclass as the effective tool (`?` in front of the block overwrite). But this might not help at all :/

**Comment by tyra314** [comment]
Second thought: does it make a difference, if you harvest to upper or lower part of the flower?

**Comment by NillerMedDild** [comment]
Nope upper/lower part doesn't change anything. I'll try the shear toolclass, but if that was the issue, they wouldn't drop when harvested by shears whether the dupe fix was on or off, right?

**Comment by NillerMedDild** [comment]
There shear toolclass, is it done like `S:"botania:doubleflower1:*"=?shears=-1`?

**Comment by NillerMedDild** [comment]
I've tried all block overwrites I could think of, none of them make the flowers drop when harvested by shears or anything else, when the dupe fix is on. I tested it in a instance with JEI, HWYLA, WAILA Harvestability, Botania and Tool Progression. Thanks for the help anyway :)

**Comment by tyra314** [comment]
The fix is part of TPr v.1.5.0, which is currently under review on curse.

**Comment by NillerMedDild** [comment]
Sweet, thank you :)
