### ISSUE TITLE
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaDataProvider

### ISSUE THREAD

**Issue by rckymtnrfc** [tyra314/ToolProgression#3]
It seems your mod has a dependency on Waila?  Is that as intended? I don't see Waila listed in the dependencies.  I'm getting the following crash without Waila installed.

https://pastebin.com/Z5rNDpfU

**Comment by tyra314** [comment]
This whole waila thingy is slowly grinding my gears...

Not intended, will fix it in the next version.

**Comment by tyra314** [comment]
Fixed in cc57007047c1024bebc7267914f3b61392ada046 and build 1.1.3

**Comment by rckymtnrfc** [comment]
Thanks for the quick fix.  Great mod!
