### ISSUE TITLE
Material Overwrites don't Affect Tinkers'

### ISSUE THREAD

**Issue by Spazmunki13** [tyra314/ToolProgression#30]
I'm using the materials_overwrites.cfg file to change wood's harvest level to -1. Vanilla tools do what I want but Tinkers' tools stay at the regular wood mining level and are still able to mine blocks that my vanilla tools can't.

**Comment by tyra314** [comment]
Sorry for the late answer.

Tools from Tinkers' Construct only read the configuration when they are created. After that point, the harvest level is stored on a per tool basis. So if you change the harvest level based on materials, you have to create new tools in order for the change to have an effect.

**Comment by Spazmunki13** [comment]
I've tried doing what you describe, making the changes, loading up the game and making new tinkers tools but they don't do as I'd expect.

Maybe I'm missing something?

These are the changes I've made to the config files:

[block_overwrites.txt](https://github.com/tyra314/ToolProgression/files/1915326/block_overwrites.txt)
[materials_overwrites.txt](https://github.com/tyra314/ToolProgression/files/1915327/materials_overwrites.txt)

But I can still use the wooden tinkers' tools on logs and stone.

**Comment by Spazmunki13** [comment]
On further investigation it seems like some of the Tinkers' tools did actually pick up the new setting while others didn't. I crafted a whole set of wooden tools at the same time and only the Hammer and Mattock are working as I would expect, they can't mine stone or cut wood. All the other tools still show "Mining Level: Wood".

**Comment by tyra314** [comment]
Interesting. I'll look into it.

**Comment by tyra314** [comment]
Tinkers Construct doesn't allow the creation of tools with a harvest level less than zero. I may be able to override this, but as a workaround, you also could increase the harvest level of stones.

Just out of curiosity, what are you trying to achieve?

**Comment by Spazmunki13** [comment]
I want to make wooden tools useless basically. I'm trying to change the progression of things a bit. But that's good to know, I'll need to workaround that.

**Comment by tyra314** [comment]
Maybe a totally different approach: Try to disable the creation of wooden tools, though I'm not sure, if crafttweaker can modify the recipes for the TiC part table (or however the thing is called, which allows to create the tool parts)

**Comment by tyra314** [comment]
As I can't do something from my side, I'll close this issue.
