### ISSUE TITLE
iguanatweaks block-hardness multiplier not working with this mod

### ISSUE THREAD

**Issue by ilvrak** [tyra314/ToolProgression#31]
some way it overlaps it. if possible - make it compatible with block hardness multiplier from iguanatweaks

toolprogression-1.12.2-1.4.7

**Comment by tyra314** [comment]
What do you mean by `overlap`?

**Comment by ilvrak** [comment]
i mean - with "toolprogression" block hardness is becoming minecraft-default. despite other mods setting hardness. like iguanatweaks, or betterwithmods stumps.

**Comment by ilvrak** [comment]
i use Harvest Tweaks instead ToolProgression and there all works fine

**Comment by tyra314** [comment]
This issue should also be fixed with the [latest ](https://minecraft.curseforge.com/projects/tool-progression/files/2566041)version.
