### ISSUE TITLE
Incompatibility with Alfinivia mod

### ISSUE THREAD

**Issue by xkforce** [tyra314/ToolProgression#32]
If tool progression is installed alongside alfinivia, block breaking speed cannot be modified via alfinivia on a block by block basis even with no configuration changes being made to tool progression.

I have also crossposted this issue to the Alfinivia issue tracker.

**Comment by DaedalusGame** [comment]
https://github.com/tyra314/ToolProgression/blob/a1902a60a6e062e55dcdf8982814cc35f894a27b/src/main/java/tyra314/toolprogression/handlers/HarvestEventHandler.java#L124

this won't work at all. if you reset the toolspeed without regarding the new speed (which is passed from other events btw) you need to run first of all (EventPriority.HIGHEST) or consider a different way of doing whatever you're doing.

**Comment by tyra314** [comment]
I can't exactly remember, why the priority is `LOWEST`. I think, it had something to do with Game-/OreStages interaction. I've to check on this.

**Comment by DaedalusGame** [comment]
oh i see now, it's because OreStages kills prior events setting the breakspeed. You can try loading after OreStages (add after:orestages to your dependencies) that should mean even if your priority is highest and orestages is highest, yours should run after.

**Comment by tyra314** [comment]
For reference: https://github.com/DaedalusGame/Alfinivia/issues/1

The fix will be part of TPr v.1.5.0, which is currently under review from curse.

**Comment by xkforce** [comment]
That was fast.  Thank you.
