### ISSUE TITLE
Quarry Issues

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#34]
Hey!

When using the RFTools Builder to quarry an area, it has a chance to throw out the block it mines into the world, if the block doesn't have an overwrite in `block_overwrites`. This issue has also been reported to RFTools.

toolprogression-1.12.2-1.5.1
rftools-1.12-7.51

https://github.com/McJtyMods/RFTools/issues/1778

**Comment by tyra314** [comment]
I can't reproduce this. Neither in my dev environment, in an instance with only RFTools and TPr, AND funnily, not even in the current released version of enigmatica expert. However, I'm unfamiliar with RFTools, maybe I'm holding it wrong...   ¯\_(ツ)_/¯

In each case, I quarry in the overworld. I set up an RF Builder with a clearing (silk) quarry card and a RFTools modular storage below the Builder. I select the area with the card and than place it into the builder. Give it a redstone signal and there we go. Hole in the world, but no dropped items.

**Comment by NillerMedDild** [comment]
Oh I forgot to mention, it only seems to happen 30% of the time for some reason (according to the original reporter), that could be why you can't replicate it.

**Comment by NillerMedDild** [comment]
Yeah I don't know what's up with that either.

It's not 30% of blocks that bug out, it's 30% of times you use the Builder for a specific place, I think.

**Comment by NillerMedDild** [comment]
Damn that's strange - Thanks for fixing it!
