### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#37]
Minecraft 1.12.2
Forge 1.12.2-14.23.4.2705
toolprogression-1.12.2-1.5.3

One of my users' server crashed after his pickaxe broke, the crashlog seems to mention Tool Progression: https://pastebin.com/RBsK85UC

**Comment by tyra314** [comment]
The pickaxe should be a funny coincidence. The crash is about an RFTools Builder being ticked.
The issue should be on my end though.

**Comment by NillerMedDild** [comment]
He managed to recreate it by breaking his pickaxe again - same crash.

**Comment by tyra314** [comment]
Interesting...

**Comment by tyra314** [comment]
It's not the pickaxe.

**Comment by tyra314** [comment]
Fixed in upcoming [1.5.4](https://minecraft.curseforge.com/projects/tool-progression/files/2572396).

**Comment by NillerMedDild** [comment]
Alright then, thank you once again :)
