### ISSUE TITLE
making wood require axe 

### ISSUE THREAD

**Issue by captainbritian** [tyra314/ToolProgression#38]
i have entered in     
#
 minecraft:log:0 [default: Axe=-1]
    S:"minecraft:log:0"=Axe=-1
in to my block overrights.cfg and it seams to just make the wood not harvistable by any axe or even the flint that i have added pickaxe=0 and axe=0 to as well i am trying to limit wood to needing a tool like in sevtech but i cannot replicate it with this mod using your own documentation

**Comment by tyra314** [comment]
If I understand you correctly, you want that players won't be able to break wood logs with bare hands?
Then you have to use at least the mining level 0. The mining level -1 is sort of still using bare hands.

So try this:
> S:"minecraft:log:0"=Axe=0

**Comment by captainbritian** [comment]
thank you i got it to work apparently capitalisation matter for this mod when you create the tool as i tried
S:"minecraft:log:0"=Axe=0 and my flint was S:"minecraft:flint"=axe=0 and to fix i just set it as the same as the flint but thank you for putting me on to the path of correcting my problem

**Comment by tyra314** [comment]
Uh, yeah sure. Size matters :)
Should have spotted that though :(
