### ISSUE TITLE
Astral Sorcery Treasure Shrine

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#39]
Hey!

Astral Sorcery treasure shrines contain a special Stone block, that regenerates when destroyed, and turns in to different ores. With Tool Progression in the same pack as Astral Sorcery, the special Stone block no longer drops anything, from any of the ores it generates. Having the correct tool and the harvest level the generated ore requires doesn't matter. 
See this issue for more details: https://github.com/HellFirePvP/AstralSorcery/issues/565#issuecomment-401535016

**Comment by tyra314** [comment]
I'm unfamiliar with AS, please provide more details.

**Comment by NillerMedDild** [comment]
If you've looked over the link, I'm not sure what more information I could give. Is there anything in particular you need to know?

**Comment by tyra314** [comment]
- I‘ve played a while with AS in my personal mod pack, but I never came across a structure with an ore block. So I don‘t even know where to find this block. 

- you mentioned overwrites in the over thread, which?

- the original poster of the other thread doesn’t have tool progression and it still happens to him

**Comment by NillerMedDild** [comment]
* It's a very rare structure found between Y 40 and 10, I don't know of a way to find one easily, appart from turning its generation chance way up in the configs.
* I was thinking the issue could be a lack of harvest level on the stone block tile entity, but that doesn't seem to be the case, as it isn't registered in the `blocks.cfg` made by TP
* The user `randomlypickedname` was able to fix the issue by just removing TP, so in the case of my modpack, it seems TP plays a part

**Comment by XavierNero** [comment]
You can find them very easily using the advanced sextant from astral sorcery, just give it yourself in creative, at night right click the night sky, if you see a large start try and drag drop the shrine onto it, if it's not a shrine it won't work, if you look at the tool tip of the sextant it tells you what you're looking for

**Comment by tyra314** [comment]
This is also fixed as part of 1.5.5

This change also fixed this issue: https://github.com/tyra314/ToolProgression/commit/dc05dc1221d307f0f012a870a9d864f809101462
