### ISSUE TITLE
minecraft blocks all having the -1(-null)

### ISSUE THREAD

**Issue by captainbritian** [tyra314/ToolProgression#40]
i dont know if this is a bug or intended but most or all of my minecraft blocks have -1(null) including the furnace and more and it drops the item its self for me this would be an error/bug as many of the blocks shouldnt be like this  like the furnace and terracotta and a few other's when the block has been broken it drops the item instead of just destroying the block

**Comment by tyra314** [comment]
Fixed in upcoming [1.5.6](https://minecraft.curseforge.com/projects/tool-progression/files/2619221)
