### ISSUE TITLE
Make the disabled TiC diamond modifier configurable

### ISSUE THREAD

**Issue by Anomerly** [tyra314/ToolProgression#41]
Hello, I have been playing with your mod and been quite excited with what I can do with it but this one thing has got me stumped.

I have added a stack of mining levels and have been going about reassigning ores and tinkers materials to give a challenging progression through different materials, but I have hit a snag.
As my material level already exceeds that which the diamond modifier should normally give me it does not progress my mining level to Diamond (Which is now 6) but leaves me where I am.

Is there a way to customise the levels that diamond and Emerald modifiers jump the selected tool up to?

**Comment by tyra314** [comment]
First, the diamond modifier is bound to mining level numbers, not names. That is a TiC issue. 
And second, this modifier should be disabled by ToolProgression. There has been an issue asking for that IIRC.

**Comment by Anomerly** [comment]
Okay, I kind of guessed it was linked to the number but is it not possible set the mining level it is linked to in a config? and enable or disable it also via config?
If your clever mod can disable it surely this is in scope for the mod?

**Comment by tyra314** [comment]
That is a feature request for tinkers construct. I may add an option to disable the disabling (or something like that).

**Comment by Anomerly** [comment]
I have created the issue with tinkers as you suggested, thank you for your direction.

Configure Diamond and emeral modifier levels #3598
https://github.com/SlimeKnights/TinkersConstruct/issues/3598

**Comment by tyra314** [comment]
I added a config option in b003cbfb561bcb76e0727e22d9319413f9f63605.
Will be part of 1.5.5
