### ISSUE TITLE
[Request] Immersive Engineering Mining Drill

### ISSUE THREAD

**Issue by WindFox** [tyra314/ToolProgression#42]
Can we get the mining drill from Immersive Engineering to be configurable?

**Comment by tyra314** [comment]
I noticed the same thing, but it wasn't high enough on my priority list. It may come in a future update if it is possible.

**Comment by tyra314** [comment]
See also: https://github.com/BluSunrize/ImmersiveEngineering/issues/3219

**Comment by tyra314** [comment]
There's no support in IE and I'm not going to hack that. Sorry :(
