### ISSUE TITLE
Incorrect names in The One Probe

### ISSUE THREAD

**Issue by WindFox** [tyra314/ToolProgression#43]
When using The One Probe, the mining level names do not change. They stay at Stone, Iron, Diamond, Obsidian, and Cobalt.

I have mine set to Stone, Bronze, Iron, Obsidian, Everything (no Cobalt).

Also, not sure if this is you or just TOP in general, but mining levels only show up in TOP for picks. Not axes or any other tool. (I have some logs needing iron level axes to actually get and TOP just says "Axe OK!")

**Comment by tyra314** [comment]
There was a TOP support issue (#18). One day it worked - a bit - so I forgot about it. I'm not sure where to start to fix this. In the meantime, I'd suggest using Waila/Hwyla and the integrated waila plugin.

**Comment by WindFox** [comment]
Only issue it that Waila/Hwyla doesn't have an item requirement mode (that I know of) The pack that I'm creating, one must hold/equip the probe it get the box to popup at all.

**Comment by MasterEnderman** [comment]
You could use the game stages mod in combination with waila stages to hide the information box until a specific game stage is unlocked.

**Comment by tyra314** [comment]
This should no work in the upcoming [v1.6.0](https://minecraft.curseforge.com/projects/tool-progression/files/2636838)
