### ISSUE TITLE
Actually Additions Block Breakers

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#44]
Hey o/

When Tool Progression is combined with Actually Additions, the 3 different block breakers from AA are unable to mine anything that requires a pickaxe. Setting them up as "tools" in the override does nothing.

toolprogression-1.12.2-1.5.4

**Comment by tyra314** [comment]
Without having checked that I suspect the AA uses a FakePlayer to break blocks. I'm not sure how to handle those in general yet.

**Comment by tyra314** [comment]
Can you provide me with a TL;DR how to use the block breaker?

**Comment by tyra314** [comment]
Nevermind. Fixed in dc05dc1221d307f0f012a870a9d864f809101462.
Will be part of 1.5.5
