### ISSUE TITLE
[1.12] Crash with Silent Gear (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by MasterEnderman** [tyra314/ToolProgression#45]
Forge: 14.23.4.2760
ToolProgression: 1.5.6
Silent Gear: 0.1.3-42
Silent Lib: 3.0.5-152

Crash Report: https://paste.dimdev.org/anilehiwif.mccrash

**Comment by tyra314** [comment]
I think this should be fixed in Silent Gear, I opened an issue there.

**Comment by tyra314** [comment]
Looks like it was fixed in SilentGear yesterday.
