### ISSUE TITLE
[1.12] Problem with Chisel & Bits "Replace" function

### ISSUE THREAD

**Issue by MasterEnderman** [tyra314/ToolProgression#46]
Chisel and bits adds a function where you can replace parts of a block with bits, while holding bits in your hand and having a chisel in the inventory. (To enter this mode select the top arrow, after opening the radial menu) By using this mod, this stops working.

**Comment by tyra314** [comment]
This should be fixed in the upcoming [v1.5.7](https://minecraft.curseforge.com/projects/tool-progression/files/2636658)
