### ISSUE TITLE
Custom Mining Level Names don't get color

### ISSUE THREAD

**Issue by duhadventure** [tyra314/ToolProgression#48]
![image](https://user-images.githubusercontent.com/8278338/48444145-b6835a00-e758-11e8-9d13-a7301cb4ef4f.png)

Right now i have the config set as this. The 0-7 are from Tinkers and its addon TAIGA and 8 should have a color of red, but It will not apply the color. It also keeps the %s as part of the name if I leave it in. 
```
mining_levels {
    # Canonical names [default: [0:Wood], [1:Stone:§8%s], [2:Iron:§f%s], [3:Diamond:§b%s]]
    S:names <
        0:Stone
        1:Iron:§7%s
        2:Diamond:§b%s
        3:Obsidian:§5%s
		4:Cobalt:§1%s
		5:Duranite§2%s
		6:Valyrium§6%s
		7:Vibranium§d%s
		8:Wyvernsteel§c
     >
}
```

**Comment by tyra314** [comment]
From looking at this, 5-8 are missing a colon `:` before the `§`.

Have you edited this config, or was it auto generated?

**Comment by duhadventure** [comment]
Edited

**Comment by tyra314** [comment]
The try this:

```
mining_levels {
    # Canonical names [default: [0:Wood], [1:Stone:§8%s], [2:Iron:§f%s], [3:Diamond:§b%s]]
    S:names <
        0:Stone
        1:Iron:§7%s
        2:Diamond:§b%s
        3:Obsidian:§5%s
        4:Cobalt:§1%s
        5:Duranite:§2%s
        6:Valyrium:§6%s
        7:Vibranium:§d%s
        8:Wyvernsteel:§c%s
     >
}
```

**Comment by duhadventure** [comment]
Yea that fixed it im just dumb

**Comment by tyra314** [comment]
Glad it works. However, this made me realize that my default levels are different from TheOneProbe and TiC 😮
