### ISSUE TITLE
Block Destroyability Problems

### ISSUE THREAD

**Issue by lynaevm** [tyra314/ToolProgression#49]
Hello!
I am having a problem with block destroyability.  In your wiki it says "By default, ToolProgression enforces that not harvestable blocks are unbreakable" which is exactly what I want.  But while I seem to be able to change the level of pickaxe or axe a block requires, I am still able to break planks, logs, and stone blocks with a piece of string in my hand.  Some drop themselves, some drop nothing, but all break.  Script lines I am using include: 
    S:"minecraft:planks:*"=axe=1
    S:"minecraft:stone:0"=pickaxe=1
which seem the same as a post about making wood planks non-harvestable with bare hands that I found in an older issue, but it doesnt' seem to work that way for me.  Are there any mod interactions or other problems I should be looking into or advice you can give?

**Comment by tyra314** [comment]
The new version [1.6.3](https://minecraft.curseforge.com/projects/tool-progression/files/2642834) adds this feature again. I also updated the documentation. Feel free to reopen, if the issue persists.
