### ISSUE TITLE
[1.12] Server NPE crash on start up

### ISSUE THREAD

**Issue by Gladi** [tyra314/ToolProgression#5]
Hey,

when I start my 1.12 Server tool progression causes a NPE error.

Crash log: http://paste.feed-the-beast.com/view/b550a7b2

Thanks

**Comment by tyra314** [comment]
Fixed in 778ac36a367e4eb0773732ba47ec13db0a015fc3 and release 1.2.3, which will soon appear on curse. thank you for reporting.
