### ISSUE TITLE
OreDict overwrites are processed to early

### ISSUE THREAD

**Issue by tyra314** [tyra314/ToolProgression#53]
From discord:

> Hey, I was having difficulty setting the harvest level of ore dictionary entries and I noticed that those entries are actually being parsed and processed before mods like IE and Mekanism are adding their ores
> It might be a bug with Underground Biomes, but, I'm seeing log messages for my attempts to override oreTin, oreCopper and oreOsmium
> I can override the individual blocks just fine, just not the oredict entries
> To be clear, the native ores don't register either with the oredict, not just the ub provided ones

**Comment by edenhack** [comment]
I see, so overwriting the block can be my workaround for now I presume. I will go this route for now then.

**Comment by tyra314** [comment]
Should be fixed in upcoming [version 1.6.6](https://minecraft.curseforge.com/projects/tool-progression/files/2693458)
