### ISSUE TITLE
Compatibility Issue with Project E

### ISSUE THREAD

**Issue by SureenInk** [tyra314/ToolProgression#55]
None of the Project E tools show up for tool overwriting. Every other mods tools seem to. Not sure if this is something fixable or not.

**Comment by tyra314** [comment]
Sorry, the harvest level is hardcoded in ProjectE itself. See [here](https://github.com/sinkillerj/ProjectE/blob/e84d844e3079b08f1303f285ea341f19f399c2ca/src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java#L80).
