### ISSUE TITLE
Conflict with Tweakers Construct

### ISSUE THREAD

**Issue by Insane96** [tyra314/ToolProgression#58]
When the ToolProgression mod is configured to change material mining levels Tweakers Construct loses all the abilities to change the durability and mining speed nerfs.

Reported to Tweakers construct too: https://github.com/RCXcrafter/TweakersConstruct/issues/18

**Comment by tyra314** [comment]
While I think that the mining speeds might just be conflicting by design, the durability issue is odd. My mod doesn't touch durability at all.

**Comment by RCXcrafter** [comment]
Fixed this on my end by changing the priority of the eventhandler.

**Comment by tyra314** [comment]
Nice. Thanks for reporting back.
