### ISSUE TITLE
Client crash when trying to mine block from Chisel & Bits

### ISSUE THREAD

**Issue by davqvist** [tyra314/ToolProgression#6]
MC 1.12
Forge 2443
TP 1.2.4

https://pastebin.com/vS9PnWgJ

A player tries to break a stone block that got chiseled with C&B and crashes everytime, no matter with what pickaxe. I haven't changed any configs in TP yet.

**Comment by tyra314** [comment]
reproduced it with just chisel&bits and tp: https://gist.github.com/tyra314/b725e2ecbe0bbe252acd390c960d05a8

**Comment by tyra314** [comment]
Fixed in upcoming 1.2.5 and 1.1.4

**Comment by davqvist** [comment]
Thanks a lot
