### ISSUE TITLE
Tinker Alloying Addon (Taiga) harvest level name overwrite

### ISSUE THREAD

**Issue by TBiscuit1** [tyra314/ToolProgression#62]
Simple! I'm making a modpack and I made every harvest level name and some harvest level name got overwrite (only on tinker tool)!

So here is the intended harvest level:
...
5: Redstone
6: Diamond
7: Obsidian
8: Ardite
9: Cobalt
...

Here is the overwrite (only affect tinker tool description)
...
5: Redstone
6: Duranite
7: Valyrium
8: Vibranium
9: Cobalt
...

Here are the screenshots:
![2019-08-14_12 16 30](https://user-images.githubusercontent.com/53101126/63037686-91f61300-be8d-11e9-96bd-e7bb77fa1619.png)
![2019-08-14_12 16 34](https://user-images.githubusercontent.com/53101126/63037694-94f10380-be8d-11e9-8f62-d484fa917a68.png)
![2019-08-14_12 16 35](https://user-images.githubusercontent.com/53101126/63037696-96223080-be8d-11e9-94f8-273d1d614601.png)
![2019-08-14_12 16 36](https://user-images.githubusercontent.com/53101126/63037698-96bac700-be8d-11e9-9a13-28898e752b85.png)
![2019-08-14_12 16 37](https://user-images.githubusercontent.com/53101126/63037699-97ebf400-be8d-11e9-8160-c44103456cea.png)

I think Taiga as priority over your mod

PS: I didn't changed the material harvest level yet (but I changed the name)

**Comment by tyra314** [comment]
I'm sorry, but I don't understand the problem?

What do you want to achieve? What have you done? What are the issues you ran into? What is the difference between the screenshots, especially, why does it work in some and in others not? I'm sorry, I am confused :(

Have you changed the `mining_level.cfg`? If so, please append it as well.

ps: The mining level at the bottom of the tooltip comes from my mod, which you can disable in the config as a short term solution.

**Comment by TBiscuit1** [comment]
Ok maybe I was not clear...
The problem is that, for tinker tool tooltip only, the mining level name is not ok
If we take the second screenshot, it say that the mlvl is Duranite in tooltip. What I wanted is that it say Diamond (which appear on your tooltip because it is not affected by TAIGA modification)
So Taiga replace the mlvl name for tinker tool tooltip, for the mlvl 6, 7 and 8 
(it replace with Duranite, Valyrium and Vibranium respectively)

So for the screenshot, it's just to make proof of what I say
So the first is to show that mlvl 5 and under is ok
The second, third and forth is to show that mlvl 6, 7 and 8 or replaced by TAIGA one (only the tinker tooltip)
and the fifth one is to show that after mlvl 8, everything is back to normal

It only affect tinker tool since TAIGA is a addon for tinker, so tools and blocks have the good mlvl name
I hope you will understand now
