### ISSUE TITLE
Version 1.6.7

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#63]
Hey o/ Would you mind un-archiving version 1.6.7? I can't get my server files approved since you've taken it down.

**Comment by NillerMedDild** [comment]
Nevermind, I just updated :)

**Comment by tyra314** [comment]
Please update to 1.6.8. The build was broken, I won’t work anyways. Therefore I archived it. 

Sorry for the inconvenience

**Comment by NillerMedDild** [comment]
No worries :)
