### ISSUE TITLE
[Suggestion] Wildcard block entries

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#8]
Hey!

Would you consider adding the ability to alter the harvestability of all metas belonging to an item? For instance, minecraft:wool:*=3 to make all wool require harvestlevel 3.

On a side note, thanks for a lot for this mod, I couldn't have made my modpack without it :D

**Comment by tyra314** [comment]
Yeah, that is on my list, but I didn't came around and fix it.

**Comment by NillerMedDild** [comment]
Awesome :D

**Comment by tyra314** [comment]
Fixed in the [new version 1.3.1](https://minecraft.curseforge.com/projects/tool-progression/files/2496568)

**Comment by NillerMedDild** [comment]
Thank you!
