### ISSUE TITLE
[Enhancement/Bug] Tool levels for Tinker modifiers (upgrades) not working

### ISSUE THREAD

**Issue by Thyriel** [tyra314/ToolProgression#9]
Hi,

not sure if this a bug or an enhancement wish but i noticed that upgrading tools with modifiers bypasses the configured mining levels from materials_overwrites.cfg
For example i set iron and emerald (which has no tools only a fluid) to mining level iron. But when upgrading an iron pickaxe with an emerald in the tool station (+50% durability) it's mining level gets increased to diamond.
Would be nice if it would be possible to change these modifier mining levels too as currently they can bypass my whole mining level system configured with your mod (and especially emerald is easy to obtain early game with villager trades)

**Comment by tyra314** [comment]
Good catch. Fixed in [1.2.10](https://minecraft.curseforge.com/projects/tool-progression/files/2493597)

**Comment by Thyriel** [comment]
Overall this is working now.
But there's one thing thats rather strange (maybe you've overseen something ?):
- Upgrading a tool with anything and then adding an emerald does NOT increase the mining level
- Upgrading a tool with anything AFTER it has been upgraded with an emerald still increases mining level
For example a bone pickaxe + silky jewel+ emerald > still mining lvl stone
but bone pickaxe + emerald + silky jewel > mining level iron

**Comment by tyra314** [comment]
Uuhh.. fixed locally. New release soon™

**Comment by tyra314** [comment]
Fix is part of release 1.2.11

**Comment by Thyriel** [comment]
Thanks, working perfectly now :)
